doctrine:
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    Core:
                        is_bundle: false
                        type: yml
                        dir: '%wiseb2b_dir%/Wise/Core/Resources/doctrine/default'
                        prefix: 'Wise\Core'
                        alias: Core
            admin:
                connection: admin
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    AdminReplication:
                        is_bundle: false
                        type: yml
                        dir: '%wiseb2b_dir%/Wise/Core/Resources/doctrine/admin'
                        prefix: 'Wise\Core\Domain\Admin'
                        alias: AdminReplication
    dbal:
        types:
            payload_bag: Wise\Core\Resources\doctrine\types\PayloadBagType
