wise_core_api_admin_v2:
  trailing_slash_on_root: false
  resource: ../../ApiAdmin/Controller/Endpoint
  type: annotation

wise_core_api_admin_v2_admin:
  trailing_slash_on_root: false
  resource: ../../ApiAdmin/Controller/Endpoint/Admin
  type: annotation

wise_core_api_ui_v2:
  trailing_slash_on_root: false
  resource: ../../ApiUi/Controller/
  type: annotation

wise_core_api_ui_endpoint_v2:
  trailing_slash_on_root: false
  resource: ../../ApiUi/Controller/Endpoint
  prefix: api/ui/
  type: annotation

wise_core_api_ui_endpoint_panel_management_v2:
  trailing_slash_on_root: false
  resource: ../../ApiUi/Controller/Endpoint/PanelManagement
  prefix: api/ui/core/panel
  type: annotation

wise_core_developer:
  trailing_slash_on_root: false
  resource: ../../Controller/
  type: annotation
